In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from scipy import optimize
from scipy.stats import multivariate_normal
import pandas as pd
import os
from math import *

In [68]:
# A=np.array([[1,2,3],[4,5,6]])
# p,s,q=np.linalg.svd(A,full_matrices=True)
# s_a=np.zeros(A.shape)
# for i in range(2): s_a[i,i]=s[i]
# p @ s_a @ q

array([[1., 2., 3.],
       [4., 5., 6.]])

In [104]:
def svd_man(A):
    C_m=A @ A.transpose()
    lam_m,q_m=np.linalg.eig(C_m)
    idx = lam_m.argsort()[::-1]         #Eigen Values and corresponding eigen vectors are sorted in descending order
    lam_m = lam_m[idx]
    q_m = q_m[:,idx]
    C_n=A.transpose() @ A
    lam_n,q_n=np.linalg.eig(C_n)
    idx = lam_n.argsort()[::-1]         #Eigen Values and corresponding eigen vectors are sorted in descending order
    lam_n = lam_n[idx]
    q_n = q_n[:,idx]
    p=q_m
    if lam_m.size<=lam_n.size:
        s=np.sqrt(lam_m) 
    else:
        s=lam_n
    q=q_n.transpose()
    return p,s,q

In [244]:
# sig=0.2
# mu=1
# l=np.arange(2,10)
# (m,n)=np.random.choice(l,2)
# A=np.random.randn(m,n)*sig + mu
# i=0
# np.linalg.svd(A)[i]-svd_man(A)[i]

array([[-5.55111512e-17, -3.33066907e-16,  3.55271368e-15,
         6.88338275e-15, -2.49800181e-15],
       [ 0.00000000e+00, -1.05471187e-15, -4.49640325e-15,
         1.02140518e-14,  5.55111512e-15],
       [ 0.00000000e+00,  1.36002321e-15,  2.66453526e-15,
         2.66453526e-15, -3.28903571e-15],
       [ 5.55111512e-17,  3.05311332e-16,  5.99520433e-15,
        -3.65818487e-14,  4.44089210e-16],
       [ 3.33066907e-16, -3.33066907e-16, -8.21565038e-15,
         2.14203655e-14, -2.22044605e-16]])

In [208]:
# np.linalg.svd(A)

(array([[-0.35356839, -0.06212127, -0.50705967, -0.23124935, -0.16919581,
         -0.44586603, -0.37488938, -0.35024732, -0.26439667],
        [-0.37303837, -0.25105525,  0.43225703, -0.34684944, -0.47205119,
          0.45354363, -0.02394147, -0.15045406, -0.19727949],
        [-0.33121293,  0.57711143,  0.60027849,  0.05619915,  0.1368159 ,
         -0.38368528, -0.14491976, -0.07923782, -0.02311768],
        [-0.32319736, -0.26965018,  0.02035018,  0.88571104, -0.13320342,
          0.03457958, -0.0629887 , -0.08794406, -0.08540163],
        [-0.30554402, -0.41109884,  0.09620215, -0.13976361,  0.82405547,
          0.10938825, -0.04484107, -0.0851328 , -0.09252217],
        [-0.26799682,  0.57941271, -0.37884469,  0.06830977,  0.14671582,
          0.6343224 , -0.12784939, -0.06267979, -0.0102198 ],
        [-0.35358825,  0.09018819, -0.16755839, -0.0468087 , -0.02236777,
         -0.15133477,  0.89481481, -0.09129975, -0.06436505],
        [-0.37087943, -0.04120399, -0.10882936, 